# Generated by Django 3.2 on 2022-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='surveyIdx',
            field=models.IntegerField(),
        ),
    ]
